### ISSUE TITLE
The get-alphas-fn should be shared across deserialized sessions for the same rulebase

### ISSUE THREAD

**Issue by WilliamParker** [cerner/clara-rules#234]
Currently Clara creates a new get-alphas-fn for each deserialized session. [1]
The get-alphas-fn caches its return value; see [2]. Since we cache empty sessions in the compiler by default, including the get-alphas-fn, the get-alphas-fn ends up being shared across multiple sessions when multiple sessions are created for the same rules and options. [3]

However, in the durability workflow, a new get-alphas-fn is created for every session. [4] As a result, return values for the get-alphas-fn are not cached between different sessions.  This is causing us significant performance problems; in one of our test workflows of durability performance around 10% of total execution time is spent in the get-alphas-fn.

I see at least three possibilities for sharing a single get-alphas-fn across sessions.

A. Have users pass in a get-alphas-fn when they deserialize a session.  This would expose Clara's implementation details to the public API though and I don't favor it for this reason.
B. Introduce a new cache of the opts->get-alphas-fn at [5].
C. Add the get-alphas-fn to the rulebase rather than having it be just a part of the session.

I am inclined toward option C since the fact-type-fn, ancestors-fn, activation-group-fn, and activation-group-sort-fn seem semantically like part of the rulebase to me; they are fundamentally part of the meaning of the rules, not tied to a specific session.  Putting them there would allow us to solve this problem without adding further API complexity in the form of a cache that users might need to manually manage (since the cache is in a way a memory leak, if you have lots of rulebases/sessions it has to be manually cleared). This distinction between the rulebase and session is similar to the distinction in Drools between the knowledge base and session.  Previously Clara didn't need such a distinction since we could just create an empty session and this session was immutable, but serializing the entire rulebase with each session when many sessions share a rulebase would have unacceptable performance impacts (so we didn't do it).

1. https://github.com/rbrush/clara-rules/blob/0.13.0-RC3/src/main/clojure/clara/rules/durability.clj#L437
2. https://github.com/rbrush/clara-rules/blob/0.13.0-RC3/src/main/clojure/clara/rules/compiler.clj#L1537
3. https://github.com/rbrush/clara-rules/blob/0.13.0-RC3/src/main/clojure/clara/rules/compiler.clj#L1673
4. https://github.com/rbrush/clara-rules/blob/0.13.0-RC3/src/main/clojure/clara/rules/durability.clj#L433
5. https://github.com/rbrush/clara-rules/blob/0.13.0-RC3/src/main/clojure/clara/rules/durability.clj#L406

**Comment by mrrodriguez** [comment]
> C. Add the get-alphas-fn to the rulebase rather than having it be just a part of the session.

+1 to this.  I don't like the API having the consumer deal with `get-alphas-fn`.  I also think the less caching we need, the better.  It is subtle complexity and does come with issues, like you said memory leaks etc.

These functions make a lot of sense to just be on the rulebase.

**Comment by rbrush** [comment]
Yep, +1 to option C as well for reasons already discussed.

**Comment by WilliamParker** [comment]
https://github.com/cerner/clara-rules/pull/235 addresses this.  I suspect @mrrodriguez will want to look at this, and possibly others as well, so I will leave this open until at least tomorrow.

**Comment by WilliamParker** [comment]
I have merged https://github.com/cerner/clara-rules/pull/235 and the Travis build is passing.  I don't see anything left to do here; I am closing this issue.
