### ISSUE TITLE
Get-alphas-fn batching is suboptimal for condition types with ancestors that also correspond to conditions

### ISSUE THREAD

**Issue by WilliamParker** [cerner/clara-rules#236]
The get-alphas-fn groups facts by type before returning them to the engine for insertion into the rules network. [1]  In combination with the iteration in flush-updates [2] the effective result is that each alpha node is activated once (with an arbitrary number of facts) per matching type in the facts to be inserted.  When fact types do not have parents that works out so that we minimize the number of alpha activations.  However, when fact types have ancestors this is not the case.  Say something like

````
(definterface Temperature)

(defrecord Cold [temperature] Temperature)

(defrecord Hot [temperature] Temperature)

(defrule cold-weather
      (?c <- [Cold])
      => ;; doesn't matter
      )

(defrule hot-weather
    (?h <- [Hot])
      => ;; doesn't matter
      )

(defrule all-weather
    (?t <- [Temperature])
            => ;; doesn't matter
            )
      

(-> (mk-session [cold-weather hot-weather all-weather])
    (insert (->Cold 0) (->Hot 100))
    fire-rules)
````

We will have one AlphaNode each for Hot, Cold, and Temperature in this rules network; these will be designated H, C, and T.  The current iteration behavior will be

- We gather the nodes matching Cold, namely C and T, and activate them.
- We gather the nodes matching Hot, namely H and T, and activate them.

Note that T is activated twice with one fact instead of once with two facts.  Since Clara is optimized for batching of operations this is inefficient.  For this simple case it is trivial, but we have a case where we will potentially have hundreds of types inheriting from a single parent.  In this case the performance is more significantly degraded.

The purpose of this issue is to track discussion to land on an approach for such batching and to implement it.  This may involve changing the behavior in all cases or making the get-alpha-fn behavior in this regard customizable in some way.  Also note that although I'm logging this issue others may be involved.  @mrrodriguez

1. https://github.com/cerner/clara-rules/blob/0.13.0-RC4/src/main/clojure/clara/rules/compiler.clj#L1555
2. https://github.com/cerner/clara-rules/blob/0.13.0-RC4/src/main/clojure/clara/rules/engine.cljc#L198

**Comment by WilliamParker** [comment]
I've been thinking about possible resolutions to this.  I implemented a draft of a replacement get-alphas-fn that would group facts by node: https://github.com/WilliamParker/clara-rules/commit/85e7aa9590a77af43edf530a8c8fa78102d92ade

In this implementation, it replaced the previous implementation, but making which is used user-configurable would also be an option.  If this benefits the cases using inheritance in their fact-types discussed above but hurts other use cases significantly I'd be inclined to leave the default as-is and make using a get-alphas-fn like this an option the user can choose, similar in spirit to our discussions of potentially offering multiple memory implementations with different performance characteristics.  We haven't done any testing of this implementation in our real-world use cases though.

**Comment by rbrush** [comment]
Seems like a good strategy. I would prefer that we just make the change you describe rather than offering a user option to change the behavior. We can debate that if we find compelling evidence of a significant performance regression for some workloads, but overall I'd like to keep the number of user-facing knobs to a minimum. In most cases I'd expect the cost of working through the Rete network to dominate any penalty from this changes, anyway.

The draft you implemented looks good. I might suggest using a local atom rather than using memoize to track the map of types and nodes. The reason is type information can change over time (by people calling Clojure's derive, etc.), and by keeping it in an atom specific to the session, users re-load the latest type hierarchy by simply creating  new session, rather than restarting Clojure itself.

**Comment by mrrodriguez** [comment]
We talked offline (well on Slack) and we think there may be a few more performance tweaks to be made to this approach as well.  The intermediate call to `platform/group-by-seq` is one of them.  Also, not creating LinkedList's when no mutation is going to happen.  As well as, avoiding the direct Collection.addAll() sort of call and prefer the approach of https://github.com/cerner/clara-rules/blob/0.13.0-RC4/src/main/clojure/clara/rules/memory.cljc#L143 for the reasons described there.

The bigger picture remains the same.  Just posting some notes on what we discussed so far.

**Comment by WilliamParker** [comment]
- On performance tweaks: agreed, I think there are some improvements that can be made here.
- On memoization: The draft memoizes a let-bound function inside create-get-alphas-fn that will be re-instantiated every time create-get-alphas-fn is called and thus given a new cache.  This seems like the same behavior we have from caching in the get-alphas-fn now, but perhaps I'm missing something. 
- On the user-facing API, making this a user-accessible knob would add complexity, which would definitely be a negative.  On the other hand, we saw significant performance degradation from the issue described in https://github.com/cerner/clara-rules/issues/234, and this draft similarly opts out of much caching that currently happens in the get-alphas-fn.  However, perhaps we can improve performance of this get-alphas-fn to a point where it doesn't matter.

**Comment by rbrush** [comment]
Ah, you're right on the memoization. (Not sure how I got my wires crossed there.)

**Comment by WilliamParker** [comment]
Second draft of this at https://github.com/WilliamParker/clara-rules/commit/b6bcea188c91f6e454cd606d510e6bfcad875470

- Removed the group-by-seq call in favor of iterating over the facts and adding them to entries in the map as appropriate.  The first draft had an iteration over all facts and then an iteration over distinct fact types; this replaces both of these with a single iteration over all facts, which I expect to improve performance.
- Removed ancestors with no matching alpha roots for insertion into the map of types to matching facts and nodes.  Since this removal happens inside a cached function, this work will only be performed once per type, while work based on ancestor types returned is performed repeatedly.
- Since the initial LinkedList creation now involves only one fact, and we don't have a previous persistent Clojure collection created for it, I don't see any benefit from a lazy transition to LinkedList anymore.  A mutable list will be created for any nonzero number of facts.
- Wrapped the fact-type in a Clojure wrapper type so that we use Clojure equality semantics, not Java ones, inside the LinkedHashMap.  The reason this is a problem is discussed at https://github.com/cerner/clara-rules/pull/195
- Wrapped the mutable lists returned inside unmodifiable views.  I am ambivalent on whether this is worthwhile since iterating over the lists and creating a view for each one will have some cost that is linear in the number of fact types present. I don't have any performance profiling results yet.

**Comment by WilliamParker** [comment]
Draft 3 at https://github.com/WilliamParker/clara-rules/commit/c4ef0d95981e061410a34c450735afd332ee9011

- Moved more work into the cached helper function and renamed it appropriately; @mrrodriguez had some good ideas on this.
- Wrapped the ancestors-fn so that a user-provided production won't match on internal system facts.  Note that since retrieving ancestors is cached inside fact-type->roots this shouldn't aggravate the issue discussed at https://github.com/cerner/clara-rules/issues/239

**Comment by WilliamParker** [comment]
I looked over this again and ran tests from our internal codebase against the changes; I think it is getting close to ready to merge if not there already.  I don't see any outstanding problems to address before doing so.  I went ahead and created a PR based on my third draft linked above. https://github.com/cerner/clara-rules/pull/242

@mrrodriguez

**Comment by WilliamParker** [comment]
Something I forgot to mention explicitly here - it looks to me like group-by-seq is doing work similar to what update-roots->facts! here does (i.e. calling the fact-type-fn and adding facts to a list based on it) and the current implementation has a map lookup based on the fact type as well.  My expectation is that this should keep any perf cost to this change in scenarios without the sort of fact type hierarchy problems discussed here to a minimum and we should therefore be able to just make this enhancement apply to all sessions rather than adding the complication of a user-facing option.  That said we might have to revisit this if we find contrary evidence from profiling.

**Comment by WilliamParker** [comment]
I have merged https://github.com/cerner/clara-rules/pull/242 for this.  I am closing this issue.
