### ISSUE TITLE
AlphaNode should keep information on its type and have a node-id

### ISSUE THREAD

**Issue by WilliamParker** [cerner/clara-rules#237]
https://github.com/cerner/clara-rules/issues/236 provided motivation for this, but it isn't really the same issue.  Our AlphaNodes in the engine currently don't have node ids; it also isn't possible to automatically inspect them to determine what type they are for.  I propose that they should have both node ids and information on their type.  So something like

````
(defrecord AlphaNode [env children activation node-id type] ...)
````

instead of the current

````
(defrecord AlphaNode [env children activation] ...)
````

The node-id would be the same as for the other nodes.  Regarding the type, suppose we had a rule

````
(defrule cold-rule
    [?c <- [Cold]]
    =>
    (insert! (->LousyWeather)))
````

The AlphaNode would have a type of Cold.

This sort of automatic inspectability would potentially be helpful for https://github.com/cerner/clara-rules/issues/236.  More generally, I think such inspectability and ability to identify a particular node would put us in a better place to write various sorts of tooling and make manual inspection of rule networks during debugging easier.  There would be some cost added to SerDe on rulebases but it should be quite small and in any case I don't think rulebase SerDe time (as opposed to session SerDe time) is particularly sensitive.

**Comment by EthanEChristian** [comment]
#450 has been merged, i will close this issue out
