### ISSUE TITLE
The get-alphas-fn in ClojureScript should wrap the fact-type-fn and ancestors-fn

### ISSUE THREAD

**Issue by WilliamParker** [cerner/clara-rules#241]
The fact-type-fn is currently wrapped to detect system types in the Clojure implementation [1] but no such wrapping exists in the ClojureScript implementation [2, 3].  This could cause the fix for https://github.com/cerner/clara-rules/issues/149 to break in ClojureScript if a custom fact-type-fn is used.  The ClojureScript implementation should also use the wrapped version on the ancestors-fn that I anticipate will be added to resolve https://github.com/cerner/clara-rules/issues/236 for reasons discussed there that are the same in Clojure and ClojureScript.

1. https://github.com/cerner/clara-rules/blob/0.13.0-RC4/src/main/clojure/clara/rules/compiler.clj#L1530
2. https://github.com/cerner/clara-rules/blob/0.13.0-RC4/src/main/clojure/clara/rules.cljc#L129
3. https://github.com/cerner/clara-rules/blob/0.13.0-RC4/src/main/clojure/clara/rules.cljc#L229

**Comment by Zylox** [comment]
I think link one is supposed to be https://github.com/cerner/clara-rules/blob/master/src/main/clojure/clara/rules/compiler.clj#L1515

**Comment by WilliamParker** [comment]
@Zylox agreed; I've updated the original post with a link to the same tag as previously.

**Comment by WilliamParker** [comment]
I've started working on this.

**Comment by WilliamParker** [comment]
I have submitted a PR to fix this at https://github.com/cerner/clara-rules/pull/295

**Comment by WilliamParker** [comment]
https://github.com/cerner/clara-rules/pull/295 fixed this issue and has been merged.  Closing.
