### ISSUE TITLE
Any remaining tasks before 0.13.0 release?

### ISSUE THREAD

**Issue by WilliamParker** [cerner/clara-rules#266]
It seems to me that we are ready for a 0.13.0 release.  Since 0.12.0, we have

- Added a vastly improved durability API that Cerner is now using in production (although this is still somewhat experimental and could have non-passive changes).
- Made several performance improvements unrelated to durability that could be significant for many use cases.  I'm particularly thinking of the improvements around alpha activations when there are fact type hierarchies involved, the improvements to external retractions, and the improvements when a custom fact type function is used.
- Greatly improved handling of exceptions in the LHS.
- Fixed bugs for several edge cases.

https://github.com/cerner/clara-rules/issues/249 is far enough away from being ready for a merge that I don't want to delay based on that.

My thinking is that we go ahead and release 0.13.0, but I wanted to check in and see if anyone has objections, particularly but not limited to the other committers, before doing so.

@rbrush @mrrodriguez

**Comment by rbrush** [comment]
+1 for making the next release 0.13.0. We had gone down the release candidate route since the early RC's were more for internal testing, but that no longer applies.

**Comment by mrrodriguez** [comment]
That sounds good to me too.

**Comment by WilliamParker** [comment]
Closing since 0.13.0 is now released.
