### ISSUE TITLE
Priorities for next (0.14.0?) release

### ISSUE THREAD

**Issue by WilliamParker** [cerner/clara-rules#272]
My thoughts are that the following should be our priorities for the next release:

- https://github.com/cerner/clara-rules/issues/268
- https://github.com/cerner/clara-rules/issues/249
- https://github.com/cerner/clara-rules/issues/267

The changes for https://github.com/cerner/clara-rules/issues/268 don't strictly speaking change any contracts, but since users could have been relying on the prior behavior of eager insertions and retractions I'm inclined to bump to 0.14.0 rather than 0.13.1 for a release with those changes.

https://github.com/cerner/clara-rules/issues/268 is done now, and https://github.com/cerner/clara-rules/issues/249 is fairly close.  I don't know if anyone has done any work on https://github.com/cerner/clara-rules/issues/267 (I have not) but it seems like a severe enough bug to me that we should get it fixed in the relatively near term.  After some investigation it seems we've been running into this as well.

Thoughts?

**Comment by rbrush** [comment]
Seems like a good list, and 0.14.0 makes sense over 0.13.1. 

I haven't had a chance to address #267 yet (too many unrelated demands), but have poked around it and have a good idea of the fix. I can grab that one next week unless someone else really wants to, and we can push 0.14.0 once these are in.

**Comment by WilliamParker** [comment]
@rbrush all yours from me on https://github.com/cerner/clara-rules/issues/267

**Comment by WilliamParker** [comment]
All of the previously mentioned issues are done now.  I think we're ready to release 0.14.0; does anyone have any thoughts and/or objections?

**Comment by rbrush** [comment]
I'm fine with a 0.14.0 release. The above features seem like they certainly justify it.

**Comment by WilliamParker** [comment]
I will proceed with releasing 0.14.0 and will close this issue when I'm done.

**Comment by WilliamParker** [comment]
The release is now complete.  Closing.
