### ISSUE TITLE
Throw exception on suspected infinite loop scenarios

### ISSUE THREAD

**Issue by WilliamParker** [cerner/clara-rules#275]
Currently when Clara enters an infinite loop it simply hangs and consumes large amounts of CPU and, depending on the loop scenario, memory.  A simple example of this is a rule like the following:

````
(defrule cold-loop
     [Cold (= ?t temperature)]
     =>
     (insert! (->Cold ?t)))
````

This scenario is obvious, but there are many less obvious scenarios that lead to loops.  Clara could set a limit on the number of iterations of the [fire-rules loop](https://github.com/cerner/clara-rules/blob/0.13.0/src/main/clojure/clara/rules/engine.cljc#L1667) that could be performed before throwing an exception indicating that the rules are likely in an infinite loop.  This number could be user-configurable; for example, the default could be a ridiculously large number of loop iterations that few if any users would actually need, with options to either change that number or eliminate the check.  The exception thrown would be an ExceptionInfo instance containing listeners and other relevant debugging information.

**Comment by rbrush** [comment]
+1 to this. Wonder what our default should be. 10,000? 100,000?

**Comment by WilliamParker** [comment]
Assigning to myself - in the event that someone else is already looking at this or wants to please let me know, but otherwise I plan to look at this over the next few weeks.  Infinite looping seems to be a persistent source of confusion based on user questions.

**Comment by WilliamParker** [comment]
This enhancement was added in https://github.com/cerner/clara-rules/pull/458.  Closing.
