### ISSUE TITLE
Accumulator record has apparently unused field

### ISSUE THREAD

**Issue by WilliamParker** [cerner/clara-rules#287]
The [Accumulator record](https://github.com/cerner/clara-rules/blob/0.14.0/src/main/clojure/clara/rules/engine.cljc#L16) has a field "input-condition" that doesn't seem to be used anywhere based on [this search](https://github.com/cerner/clara-rules/search?utf8=%E2%9C%93&q=input-condition&type=).  According to Git Blame the line dates back to this [early refactoring commit](https://github.com/cerner/clara-rules/commit/7df4b9a2cb6195d4ebef613e763934d85f8cda72).  A quick glance through the code then suggests that the structure of accumulation in the rules network was significantly different then.  @rbrush I think that field can be removed from the accumulator record definition?

**Comment by rbrush** [comment]
Yes, I think this can be safely removed for the reasons you mention.

**Comment by WilliamParker** [comment]
Addressed by https://github.com/cerner/clara-rules/commit/0d9384295d84260031e1ec595c6389af7f8ff25f

Closing.
