### ISSUE TITLE
Plans for 0.15.0 release

### ISSUE THREAD

**Issue by WilliamParker** [cerner/clara-rules#294]
Major improvements since 0.14.0:

- https://github.com/cerner/clara-rules/issues/276 has improved inspection on rules with accumulator conditions.
- https://github.com/cerner/clara-rules/issues/280 fixed a memory leak and corrected a confusing case in session inspection where we could have data structures with no meaningful data returned that should just have not been created at all.
- https://github.com/cerner/clara-rules/issues/277 added functionality to create a graph data structure of facts and what insertions they caused.
- https://github.com/cerner/clara-rules/issues/289 added negation conditions to the :condition-matches in session inspection.

Overall I think this is enough improvement to session inspection tooling to justify a release; https://github.com/cerner/clara-rules/issues/277 in particular seems to have attracted some interest in the community.  The last release was cut on March 22.

Since the ClojureScript version is attracting increased interest, and we'll be signaling that salience is supported in ClojureScript with https://github.com/cerner/clara-rules/issues/285 and https://github.com/cerner/clara-rules/pull/288 I'd like to go ahead and get https://github.com/cerner/clara-rules/issues/241 done before releasing.  It should be a pretty straightforward and easy one; if nobody else wants to work on that I'll plan on taking care of it. 
 IMO once that is done we should release 0.15.0.

Thoughts?

**Comment by WilliamParker** [comment]
@rbrush @mrrodriguez

**Comment by mrrodriguez** [comment]
Makes sense to me. I see you have taken on the last #241  now too.

**Comment by rbrush** [comment]
+1 for the release from me as well.

**Comment by WilliamParker** [comment]
I'm starting to create the release.  I'll comment here and close this issue when I'm done.

**Comment by WilliamParker** [comment]
The release is now available; closing.
