### ISSUE TITLE
Questions about changing Apache 2.0 license

### ISSUE THREAD

**Issue by alex-dixon** [cerner/clara-rules#299]
Just wondering if there's any way you might be open to licensing Clara under MIT or EPL. 

I'm working on a framework that takes Clara as its main dependency and have concerns about Apache 2.0 Mainly I'm concerned about people's concerns and the hesitation I've seen with non-MIT licensed software in commercial settings. 

I know the MIT license from the Javascript/Node community is the gold standard for "use this in a commercial product or however you want, basically". I'm less familiar with EPL (Eclipse Public License), just that every Clojure project I've seen uses it, along with Clojure itself. The little research I've done on it makes it seem equally permissive, though I think the perception is that it's "less safe" than MIT in commercial settings in particular.

No hurry to respond as I may be further from releasing the framework than I would like but was just doing some housecleaning and thought I'd bring it up now. 

Hope everyone's well. :)

**Comment by rbrush** [comment]
Hey Alex, 

We've normalized all of Cerner's open source projects on the Apache license, and would prefer not to have exceptions unless there is really a compelling reason to do so. The license itself is pretty liberal -- we use a lot of Apache-licensed software in our commercial systems -- so I don't think there should be any problem there (but of course I am not qualified to offer legal advice). 

We can consider options if there is a particular problem with the Apache License...but like I said it's probably something we'd be reluctant to do.

-Ryan

**Comment by alex-dixon** [comment]
Understood. Had to ask :) Thanks for your response.
