### ISSUE TITLE
Upgrading schema library

### ISSUE THREAD

**Issue by alex-dixon** [cerner/clara-rules#306]
Hello! i apologize for not mentioning to this to Clara directly in advance, but I've made a framework called Precept that wraps Clara in eav tuple syntax and is presently aimed to support client-side development. I'm trying my best to give Clara its due credit, and I am very grateful for the hard work you've put in to make it possible to run a fully-fledged rule engine in the browser. I'd appreciate any feedback you could provide if and whenever you have the time.

Ok, so I'm wondering if you want to consider upgrading your version of schema to 1.1.6. It seems Clara's version breaks for users of Clojure 1.9.0-alpha17 and Clojurescript 1.9.562. Our tests pass with the old schema version but we get errors running a CLJS app.
 
https://github.com/CoNarrative/precept/pull/79

**Comment by mrrodriguez** [comment]
I'm not necessarily opposed to making this change. The schema version is starting to lag and there have been quite a few changes. https://github.com/plumatic/schema/blob/master/CHANGELOG.md#111 is the most aggressive one I've seen so far. It actually broke something I was working on that had a clash of versions of schema both on the classpath (AOT-drama).

-----

I find a few points of interest here for additional background info collection:

1) Is schema "1.0.1" reported to break in current versions of cljs and clj? I don't see any reference to this. It is odd that it is breaking on a `schema.core/validate` call on a basic persistent map impl.

2) The cljs warnings have all been mentioned and addressed in recent schema versions according to the  changelog's https://github.com/plumatic/schema/blob/master/CHANGELOG.md

3) Am I correct that https://github.com/CoNarrative/precept is not actually using the schema dependency directly (it only is pulling it transitively)? I do not see it require'd in any of the namespaces there.
I'm double checking on that point, just to determine if the fix seems inappropriate. If you don't use the schema lib at all, you shouldn't have to be concerned with it.

**Comment by alex-dixon** [comment]
@mrrodriguez Correct. The PR would be adding it in order to support the newer versions of CLJ/CLJS. We don't use it for anything.

**Comment by WilliamParker** [comment]
On using Clara in Precept, no problem.  Glad it is useful. :)

On the Schema version, the proposal is just to update the version Clara uses in its own project.clj, not change Clara in a way that would break usage of the current version (e.g. by using new features in Schema), correct?  Clara built on my machine when I bumped the Schema version to 1.1.6 without any additional changes and from the [Schema changelog](https://github.com/plumatic/schema/blob/master/CHANGELOG.md) I don't see anything between 1.0.1 and 1.1.6 that looks like it would break Clara's usage of Schema.

**Comment by mrrodriguez** [comment]
I think an upgrade sounds reasonable. My only other point though is I don't really understand why the precept error was happening. I don't see anything in schema that was broken and fixed between these versions.

**Comment by alex-dixon** [comment]
I would expect the same error in a project that uses the latest versions of Clojure and Clojurescript. I thought maybe Clojure.spec was the culprit but I've no clear reason for thinking that. The errors I coped in [here](https://github.com/CoNarrative/precept/pull/79) reference Schema.spec and the accumulators namespace.

**Comment by WilliamParker** [comment]
I think the relevant change in Schema is [PR 393](https://github.com/plumatic/schema/pull/393/files); basically a symbol Schema defines is now a symbol in core.cljs after https://github.com/clojure/clojurescript/commit/78891af8b68899e0e0456161116aeab23d1c031a for [CLJS-2013](https://dev.clojure.org/jira/browse/CLJS-2013).  The failure @alex-dixon  pointed to contained

````
No protocol method Schema.spec defined for type cljs.core/PersistentArrayMap
````

so it seems likely that this is related to the MapEntry issue although I haven't dug into the Precept code that failed.

**Comment by mrrodriguez** [comment]
@WilliamParker I mentioned in my original comment above https://github.com/cerner/clara-rules/issues/306#issuecomment-307231280 on point (2) that several warnings have been addressed.

The exception doesn't appear to be the same as those warnings though. That is where I was surprised because I had not heard of anything actually broken in any recent versions schema against any recent versions of cljs. The no protocol impl on PersistentArrayMap is strange. It has been impl'ed on that data type for quite a while, including the version Clara is running
https://github.com/plumatic/schema/blob/schema-1.0.1/src/cljx/schema/core.cljx#L763-L764

So I was curious if there was some sort of cross-dependency interaction or AOT-related thing going on here that is actually the source of trouble. It seems increasing the version helps, but that could be due to these integration sorts of interactions.

**Comment by mrrodriguez** [comment]
+1 to the schema uplift regardless. 

It'd be nice to reproduce for better understanding, but that doesn't have to prevent it.

**Comment by WilliamParker** [comment]
There doesn't seem to be any objection of bumping our Schema version so I have merged https://github.com/cerner/clara-rules/pull/311

**Comment by alex-dixon** [comment]
Thanks!
