### ISSUE TITLE
Distinct accumulator does not handle duplicate values during retractions of a subset of them

### ISSUE THREAD

**Issue by WilliamParker** [cerner/clara-rules#325]
I'd expect the following test to pass but it fails.

````
(def-rules-test test-distinct-duplicates
  {:queries [distinct-temp-locations [[] [[?locations <- (acc/distinct :location) from [Temperature]]]]]
   :sessions [empty-session [distinct-temp-locations] {}]}

  (is (= [{:?locations #{"MCI"}}]
         (-> empty-session
             (insert (->Temperature 80 "MCI") (->Temperature 100 "MCI"))
             fire-rules
             (retract (->Temperature 80 "MCI"))
             fire-rules
             (query distinct-temp-locations)))))
````

The cause of this is that the retract functions for the [distinct accumulator](https://github.com/cerner/clara-rules/blob/0.15.1/src/main/clojure/clara/rules/accumulators.cljc#L170), both with and without a field function given, simply remove the value in question from the set of distinct values without considering whether a duplicate fact exists or whether another, non-duplicate fact with the same field value exists.

**Comment by WilliamParker** [comment]
I have created a PR for this at https://github.com/cerner/clara-rules/pull/326

**Comment by WilliamParker** [comment]
The PR has been merged.  IMO a 0.15.2 release with this would be appropriate; are there any objections to that?

**Comment by rbrush** [comment]
No objections here.

**Comment by WilliamParker** [comment]
The PR has been merged and the release has been cut.

Closing.
