### ISSUE TITLE
Plans for next (0.16.1?) release

### ISSUE THREAD

**Issue by WilliamParker** [cerner/clara-rules#354]
It seems to me that there have been enough changes since 0.16.0 to justify cutting a release.  The largest of these is https://github.com/cerner/clara-rules/pull/342 IMO.  Nothing since 0.16.0 should require bumping to 0.17.0 in my opinion since everything is one of:

- a bugfix (https://github.com/cerner/clara-rules/pull/346, https://github.com/cerner/clara-rules/issues/304, https://github.com/cerner/clara-rules/issues/352)
- Consistently choosing a return type in a case where that type was previously only sometimes chosen (https://github.com/cerner/clara-rules/issues/338)
- improving parser validation (https://github.com/cerner/clara-rules/pull/349).
- Refactoring with no API impact (https://github.com/cerner/clara-rules/pull/339).  Note that this one also improves performance of session inspection considerably.
- Test-only changes

Thoughts?

**Comment by rbrush** [comment]
Agreed there is more than enough for a new release here, and 0.16.1 makes sense to me.

**Comment by WilliamParker** [comment]
I have cut release 0.16.1 with a [tag here](https://github.com/cerner/clara-rules/tree/0.16.1) and it is now [available on Clojars](https://clojars.org/com.cerner/clara-rules/versions/0.16.1).

Closing.
