### ISSUE TITLE
Plans for next release

### ISSUE THREAD

**Issue by WilliamParker** [cerner/clara-rules#370]
Since 0.16.1 we have:

- Added support for session inspection and fact-graph to ClojureScript.  [Issue 307](https://github.com/cerner/clara-rules/issues/307).
- Added functionality for live reloading in ClojureScript.  [Issue 316](https://github.com/cerner/clara-rules/issues/316)
- Fixed a significant bug in symbol qualification in ClojureScript. [Issue 359](https://github.com/cerner/clara-rules/issues/359)

Currently in progress:
- Add additional information to listener methods. [PR 366](https://github.com/cerner/clara-rules/pull/366)
- Refactoring to support custom user DSL macros. [Issue 362](https://github.com/cerner/clara-rules/issues/362)

The 3 things in master would justify a 0.16.2 release IMO and its been a while since the last release of 0.16.1 on Nov. 1.  There are some minor points to address in both PRs, so I'm not sure whether we want to wait for them to release.  In any case we can release later once they are done as well, we don't have to wait 2 months between releases. :)

In terms of versioning, [PR 366](https://github.com/cerner/clara-rules/pull/366) would require bumping to version 0.17.0.  Refactoring to support custom user DSL macros. [Issue 362](https://github.com/cerner/clara-rules/issues/362) could be done in a 0.16.x release.  I don't see a need to create a separate minor release apart from a 0.17.0 release if we do that though unless someone has a particular need for it.

Thoughts?

@sparkofreason @alex-dixon @mrrodriguez @rbrush

**Comment by alex-dixon** [comment]
0.17.0 for me. Onward!

**Comment by WilliamParker** [comment]
I'll plan to release 0.17.0 with the changes in master sometime over the coming week (or possibly the next if this one is too busy) whenever my time permits unless objections are raised or someone else does it first. :)

**Comment by WilliamParker** [comment]
The 0.17.0 release is available on Clojars: https://clojars.org/com.cerner/clara-rules/versions/0.17.0

Closing this issue.
