### ISSUE TITLE
Update copyright year?

### ISSUE THREAD

**Issue by alex-dixon** [cerner/clara-rules#372]
Just curious whether the copyright year (2016) can be updated to 2018. :)

Shows 2016 here: https://github.com/cerner/clara-rules/blob/master/README.md. Guessing other places as well.

**Comment by WilliamParker** [comment]
@alex-dixon : Just letting you know that I've seen this.  Any change to legal notices/licensing may require some discussion within Cerner.

**Comment by WilliamParker** [comment]
Ryan addressed this with https://github.com/cerner/clara-rules/commit/48ddd5935b35ee395c94f7e8a302b1d322fe5c66

Closing.
