### ISSUE TITLE
Enhance performance while adding conjunctions in beta graph construction

### ISSUE THREAD

**Issue by EthanEChristian** [cerner/clara-rules#377]
Profiling locally indicates that there is a bit of a hotspot in beta graph construction, specifically [add-conjunctions](https://github.com/cerner/clara-rules/blob/0.17.0/src/main/clojure/clara/rules/compiler.clj#L1052).
There are probably other hot spots but this one stood out as a potentially easy one to solve, this issue lies with the `sorted-set` and the `first` call on the for loop seen [here](https://github.com/cerner/clara-rules/blob/0.17.0/src/main/clojure/clara/rules/compiler.clj#L1081-L1098).

The sorted nature of the set of forward edges must be maintained to provide consistent session creation, however we could potentially save some time if we had a different approach.

**Comment by EthanEChristian** [comment]
I have a working branch, and i plan on posting a Pull request soon

**Comment by WilliamParker** [comment]
I've merged the PR.  Enhancements to minimize calls to try-eval can be further discussed on https://github.com/cerner/clara-rules/issues/381.  Closing the issue, thanks @EthanEChristian
