### ISSUE TITLE
ClojureScript support limited to compile-time fire-rules?

### ISSUE THREAD

**Issue by gamecubate** [cerner/clara-rules#430]
According to the Wiki entry on ClojureScript, my understanding is that I wouldn't be able to use clara-rules to build a pure front-end web app with facts-feeding form inputs, the onChange events of which would trigger fire-rules calls, ultimately resulting in updated "answer" content.

Is this correct?

**Comment by mrrodriguez** [comment]
@gamecubate 

In CLJS the rule network itself has to be compiled via the CLJS compiler. This means that a rule network cannot be built (at least not easily), dynamically from within the compiled JS.

However, `fire-rules` and other functions interacting with a rules sessions can, and really always are, worked with from within the actual CLJS compiled JS. You can indeed attach Clara rule session actions to event handlers such as `onChange`.

For a concrete example, the https://github.com/CoNarrative/precept library is actually built around this sort of behavior.

**Comment by gamecubate** [comment]
That's very good news. Thanks for the clarification. I had been misunderstood `Therefore the ClojureScript version needs to use pre-defined rule sessions rather than generating them on the fly.` to mean that one could not, for example, call mk-session from within transpiled, optimized, cljs code.
