### ISSUE TITLE
0.20.0 release plans

### ISSUE THREAD

**Issue by WilliamParker** [cerner/clara-rules#440]
I suggest that we create a 0.20.0 release with the changes made to fix

- [issue 417](https://github.com/cerner/clara-rules/issues/417)
- [issue 433](https://github.com/cerner/clara-rules/issues/433)

and add the performance optimization created in  [issue 422](https://github.com/cerner/clara-rules/issues/422).
My reason for going with a 0.20.0 release rather than 0.19.2 would be that the changes in [issue 422](https://github.com/cerner/clara-rules/issues/422) could cause some users to need to set the new :omit-compile-ctx setting.

**Comment by EthanEChristian** [comment]
I think the minor version makes sense.

**Comment by WilliamParker** [comment]
I'll plan to release to cut a release Saturday unless there are objections. cc @mrrodriguez

**Comment by mrrodriguez** [comment]
Sounds fine to me 👍

**Comment by WilliamParker** [comment]
I've created a tag but am having unforeseen difficulties with GPG so it may take some time.

**Comment by WilliamParker** [comment]
Release complete, closing.
