### ISSUE TITLE
Rename 'master' branch to 'main'

### ISSUE THREAD

**Issue by kpshek** [cerner/clara-rules#461]
At Cerner, we are renaming the 'master' branch within our repositories to 'main'. This is to encourage a more inclusive culture, better reflects the purpose of the branch, and aligns with other communities and [GitHub's direction](https://twitter.com/natfriedman/status/1271253144442253312).

In addition to renaming the branch, there are a few references here in the repository that will need to be updated:
https://github.com/cerner/clara-rules/search?q=master&unscoped_q=master

**Comment by EthanEChristian** [comment]
Main branch created:
https://github.com/cerner/clara-rules/tree/main

**Comment by EthanEChristian** [comment]
@kpshek,

I believe all should be in order now. Can you confirm that everything is satisfactory?

cc. @mrrodriguez

**Comment by kpshek** [comment]
Looks great - thank you @EthanEChristian! ❤️

**Comment by EthanEChristian** [comment]
Thanks for logging this issue @kpshek.
