### ISSUE TITLE
Plans for 0.21.0 release

### ISSUE THREAD

**Issue by WilliamParker** [cerner/clara-rules#462]
Since the 0.20.0 release we have these changes:

- Added type information to AlphaNode for introspection: [issue 237](https://github.com/cerner/clara-rules/issues/237).
- Fixed a bug with facts that have IndexedPropertyDescriptor fields: [issue 446](https://github.com/cerner/clara-rules/issues/446).
- Added class names to anonymous functions in Clara so that those names will show up in performance profiling. [issue 261](https://github.com/cerner/clara-rules/issues/261) and [issue 291](https://github.com/cerner/clara-rules/issues/291).
- Error checking on query parameters. [issue 454](https://github.com/cerner/clara-rules/issues/454)
- Added a listener that allows detection of likely infinite loops in rules. [issue 275](https://github.com/cerner/clara-rules/issues/275)

I think there's enough here to warrant a release and it has been some time.  Since there are new features I think we can bump to 0.21.0 as opposed to 0.20.1.

Thoughts @EthanEChristian @mrrodriguez ? Is there anything else you'd like to get in before releasing?

**Comment by EthanEChristian** [comment]
That looks like plenty of issues to necessitate a release, thanks @WilliamParker.

**Comment by WilliamParker** [comment]
The release is now available on Clojars.
